# Generated by Django 5.2.8 on 2025-11-15 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome CCNL')),
                ('n_mensilita', models.SmallIntegerField(default=13, verbose_name='Numero Mensilità Annuali')),
            ],
            options={
                'verbose_name': 'CCNL',
                'verbose_name_plural': 'CCNL',
            },
        ),
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_settimanali', models.SmallIntegerField(blank=True, null=True, verbose_name='Ore Settimanali (1-40, Null per P.IVA/Occasionale)')),
                ('tipo', models.CharField(choices=[('IND', 'Indeterminato'), ('DET', 'Determinato'), ('SOST', 'Sostituzione'), ('OCC', 'Occasionale'), ('PIVA', 'Partita IVA')], default='IND', max_length=4, verbose_name='Tipo di Contratto')),
                ('dal', models.DateField(verbose_name='Data Inizio Contratto')),
                ('al', models.DateField(blank=True, null=True, verbose_name='Data Fine Contratto')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note Contratto')),
                ('ccnl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratti_associati', to='contratti.ccnl', verbose_name='CCNL di Riferimento')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratti', to='dipendenti.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Contratto',
                'verbose_name_plural': 'Contratti',
                'ordering': ['-dal'],
            },
        ),
        migrations.CreateModel(
            name='Straordinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField(verbose_name='Data e Ora Inizio Straordinario')),
                ('fine', models.DateTimeField(verbose_name='Data e Ora Fine Straordinario')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='straordinari', to='contratti.contratto', verbose_name='Contratto di Riferimento')),
                ('utente_richiedente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente Richiedente/Registrante')),
            ],
            options={
                'verbose_name': 'Straordinario',
                'verbose_name_plural': 'Straordinari',
                'ordering': ['-inizio'],
            },
        ),
        migrations.CreateModel(
            name='BustaPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.SmallIntegerField(verbose_name='Anno di Riferimento')),
                ('mese', models.SmallIntegerField(verbose_name='Mese di Riferimento (1-12)')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Caricamento Documento')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrizione del Documento')),
                ('tipo', models.CharField(choices=[('PAGA', 'Busta Paga'), ('13', 'Tredicesima'), ('14', 'Quattordicesima'), ('TFR', 'TFR'), ('ATFR', 'Anticipo TFR'), ('FATT', 'Fattura'), ('ALTRO', 'Altro')], default='PAGA', max_length=5, verbose_name='Tipo di Documento')),
                ('file_documento', models.FileField(blank=True, null=True, upload_to='buste_paga/', verbose_name='File Busta Paga/Fattura (PDF, ecc.)')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buste_paga_emesse', to='contratti.contratto', verbose_name='Contratto di Riferimento')),
            ],
            options={
                'verbose_name': 'Busta Paga/Documento di Pagamento',
                'verbose_name_plural': 'Buste Paga/Documenti di Pagamento',
                'ordering': ['-anno', '-mese'],
                'unique_together': {('contratto', 'anno', 'mese', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='OrariContrattuali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='Giorno della Settimana (DOW)')),
                ('f1_start', models.TimeField(blank=True, null=True, verbose_name='Fascia 1 Inizio')),
                ('f1_end', models.TimeField(blank=True, null=True, verbose_name='Fascia 1 Fine')),
                ('f2_start', models.TimeField(blank=True, null=True, verbose_name='Fascia 2 Inizio')),
                ('f2_end', models.TimeField(blank=True, null=True, verbose_name='Fascia 2 Fine')),
                ('f3_start', models.TimeField(blank=True, null=True, verbose_name='Fascia 3 Inizio')),
                ('f3_end', models.TimeField(blank=True, null=True, verbose_name='Fascia 3 Fine')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orari', to='contratti.contratto', verbose_name='Contratto di Riferimento')),
            ],
            options={
                'verbose_name': 'Orario Contrattuale',
                'verbose_name_plural': 'Orari Contrattuali',
                'ordering': ['contratto', 'dow'],
                'unique_together': {('contratto', 'dow')},
            },
        ),
    ]
