# Generated by Django 5.2.8 on 2025-11-16 14:30

from django.db import migrations

APP = 'contratti'
MODEL = 'Ccnl'

UNIQUE_KEY = 'nome'

RECORDS = [
    {
        'nome': 'Commercio, Terziario e Servizi',
        'n_mensilita': 14,
    },
    {
        'nome': 'Metalmeccanica',
        'n_mensilita': 13,
    },
    {
        'nome': 'Pulizie/Multiservizi',
        'n_mensilita': 13,
    },
]


def crea(apps, schema_editor):
    """
    Funzione eseguita in fase di avanzamento (forward) della migrazione.
    Inserisce i tipi di assenza se non esistono.
    """
    Modello = apps.get_model(APP, MODEL)
    
    for data in RECORDS:
        key = data[UNIQUE_KEY]
        
        # Logica di Idempotenza: crea solo se il record non esiste
        if not Modello.objects.filter(**{UNIQUE_KEY: key}).exists():
            Modello.objects.create(**data)

            print(f"Creato {MODEL}: {key}")
        else:
            print(f"{MODEL}: {key} già esistente. Salto la creazione.")


def elimina(apps, schema_editor):
    """
    Funzione eseguita in caso di rollback (reverse) della migrazione.
    Elimina i tipi di assenza inseriti, assumendo che i nomi siano univoci.
    """
    Modello = apps.get_model(APP, MODEL)
    
    keys_da_eliminare = [data[UNIQUE_KEY] for data in RECORDS]
    
    deleted_count, _ = Modello.objects.filter(**{f"{UNIQUE_KEY}__in": keys_da_eliminare}).delete()
    print(f"Eliminati {deleted_count} {MODEL} in fase di rollback.")

class Migration(migrations.Migration):

    dependencies = [
        ('contratti', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crea, elimina),
    ]
