# Generated by Django 5.2.8 on 2025-11-14 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=100, verbose_name='Cognome')),
                ('codice_fiscale', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z]$')], verbose_name='Codice Fiscale')),
                ('data_nascita', models.DateField(verbose_name='Data di Nascita')),
                ('comune_nascita', models.CharField(max_length=150, verbose_name='Comune di Nascita')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note Varie (Patente, Invalidità, ecc.)')),
                ('utente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dipendente_profilo', to=settings.AUTH_USER_MODEL, verbose_name='Utente Django (Login)')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CellulareDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellulare', models.CharField(max_length=20, unique=True, verbose_name='Numero di Cellulare')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('principale', models.BooleanField(default=False, verbose_name='Cellulare Principale')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellulari', to='dipendenti.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Cellulare Dipendente',
                'verbose_name_plural': 'Cellulari Dipendenti',
                'constraints': [models.UniqueConstraint(condition=models.Q(('attivo', True), ('principale', True)), fields=('dipendente',), name='unico_cellulare_principale_attivo')],
            },
        ),
        migrations.CreateModel(
            name='EmailDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Indirizzo Email')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('principale', models.BooleanField(default=False, verbose_name='Email Principale')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='dipendenti.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Email Dipendente',
                'verbose_name_plural': 'Email Dipendenti',
                'constraints': [models.UniqueConstraint(condition=models.Q(('attivo', True), ('principale', True)), fields=('dipendente',), name='unico_email_principale_attiva')],
            },
        ),
        migrations.CreateModel(
            name='IbanDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('dal', models.DateField(verbose_name='Data Inizio Validità')),
                ('al', models.DateField(blank=True, null=True, verbose_name='Data Fine Validità')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibans', to='dipendenti.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'IBAN Dipendente',
                'verbose_name_plural': 'IBAN Dipendenti',
                'constraints': [models.UniqueConstraint(fields=('dipendente', 'iban', 'dal'), name='unique_dipendente_iban_dal')],
            },
        ),
        migrations.CreateModel(
            name='IndirizzoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Residenza'), ('D', 'Domicilio')], max_length=1, verbose_name='Tipo di Indirizzo')),
                ('nazione', models.CharField(default='Italia', max_length=100, verbose_name='Nazione')),
                ('regione', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regione')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('citta', models.CharField(max_length=150, verbose_name='Città')),
                ('cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Via/Piazza')),
                ('civico', models.CharField(blank=True, max_length=20, verbose_name='Numero Civico')),
                ('dal', models.DateField(verbose_name='Data Inizio Validità')),
                ('al', models.DateField(blank=True, null=True, verbose_name='Data Fine Validità')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to='dipendenti.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Indirizzo Dipendente',
                'verbose_name_plural': 'Indirizzi Dipendenti',
                'constraints': [models.UniqueConstraint(fields=('dipendente', 'tipo', 'dal'), name='unique_dipendente_tipo_dal')],
            },
        ),
    ]
