# Generated by Django 5.2.8 on 2025-11-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAssenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Tipo Assenza')),
                ('richiede_approvazione', models.BooleanField(default=True, verbose_name='Richiede Approvazione Manageriale')),
                ('id_nazionale_default', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Nazionale/PUK di Riferimento (Default)')),
            ],
            options={
                'verbose_name': 'Tipo di Assenza',
                'verbose_name_plural': 'Tipi di Assenza',
            },
        ),
        migrations.CreateModel(
            name='Assenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data Assenza')),
                ('giornata_intera', models.BooleanField(default=True, verbose_name='Giornata Intera')),
                ('inizio', models.DateTimeField(blank=True, null=True, verbose_name='Ora Inizio Assenza (se parziale)')),
                ('fine', models.DateTimeField(blank=True, null=True, verbose_name='Ora Fine Assenza (se parziale)')),
                ('id_nazionale', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Assenza Esterno (es. PUK Malattia)')),
                ('approvata', models.BooleanField(default=False, verbose_name='Assenza Approvata')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to='contratti.contratto', verbose_name='Contratto di Riferimento')),
                ('utente_approvazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assenze_approvate', to=settings.AUTH_USER_MODEL, verbose_name='Utente Approvazione')),
                ('utente_inserimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assenze_inserite', to=settings.AUTH_USER_MODEL, verbose_name='Utente Inserimento')),
                ('tipo_assenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assenze_associate', to='assenze.tipoassenza', verbose_name='Tipo di Assenza')),
            ],
            options={
                'verbose_name': 'Assenza',
                'verbose_name_plural': 'Assenze',
                'ordering': ['-data'],
            },
        ),
    ]
