# Generated by Django 5.2.8 on 2025-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoassenza',
            name='id_nazionale_default',
        ),
        migrations.AddField(
            model_name='tipoassenza',
            name='codice_assenza',
            field=models.CharField(default='A', max_length=5, verbose_name='Codice assenza'),
        ),
        migrations.AddField(
            model_name='tipoassenza',
            name='richiede_id_nazionale',
            field=models.BooleanField(default=False, verbose_name='Richiede un id nazionale'),
        ),
    ]
