# Generated by Django 5.2.8 on 2025-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0002_remove_tipoassenza_id_nazionale_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoassenza',
            name='richiesta_dipendente',
            field=models.BooleanField(default=False, verbose_name='Richiedibile dal dipendente'),
        ),
    ]
