# Generated by Django 5.2.8 on 2025-11-15 13:56

from django.db import migrations

TIPI_ASSENZA_INIZIALI = [
    {
        'nome': 'Malattia',
        'richiesta_dipendente': False,
        'richiede_approvazione': False,
        'richiede_id_nazionale': True,
        'codice_assenza':  'M',
    },
    {
        'nome': 'Legge 104',
        'richiesta_dipendente': False,
        'richiede_approvazione': False,
        'richiede_id_nazionale': False,
        'codice_assenza':  'L104',
    },
    {
        'nome': 'Infortunio',
        'richiesta_dipendente': False,
        'richiede_approvazione': False,
        'richiede_id_nazionale': True,
        'codice_assenza':  'I',
    },
    {
        'nome': 'Ferie',
        'richiesta_dipendente': True,
        'richiede_approvazione': True,
        'richiede_id_nazionale': False,
        'codice_assenza':  'F6',
    },
    {
        'nome': 'Permesso Ex Festività',
        'richiesta_dipendente': True,
        'richiede_approvazione': True,
        'richiede_id_nazionale': False,
        'codice_assenza':  'E0',
    },
    {
        'nome': 'Festività',
        'richiesta_dipendente': False,
        'richiede_approvazione': False,
        'richiede_id_nazionale': False,
        'codice_assenza':  'F',
    },
    {
        'nome': 'Maternità',
        'richiesta_dipendente': False,
        'richiede_approvazione': False,
        'richiede_id_nazionale': True,
        'codice_assenza':  'MT',
    },
    {
        'nome': 'Permesso Retribuito (ROL/Ora)',
        'richiesta_dipendente': True,
        'richiede_approvazione': True,
        'richiede_id_nazionale': False,
        'codice_assenza':  'P',
    },
    {
        'nome': 'Congedo Parentale',
        'richiesta_dipendente': True,
        'richiede_approvazione': False,
        'richiede_id_nazionale': True,
        'codice_assenza':  'CP',
    },
    {
        'nome': 'Congedo Matrimoniale',
        'richiesta_dipendente': True,
        'richiede_approvazione': False,
        'richiede_id_nazionale': False,
        'codice_assenza':  'CM',
    },
    {
        'nome': 'Permesso Studio Retribuito (Diritto allo Studio)',
        'richiesta_dipendente': True,
        'richiede_approvazione': True,
        'richiede_id_nazionale': False,
        'codice_assenza':  'ST',
    },
    {
        'nome': 'Aspettativa Non Retribuita',
        'richiesta_dipendente': True,
        'richiede_approvazione': True,
        'richiede_id_nazionale': False,
        'codice_assenza':  'ANR',
    },
    {
        'nome': 'Permesso per Lutto',
        'richiesta_dipendente': True,
        'richiede_approvazione': False,
        'richiede_id_nazionale': False,
        'codice_assenza':  'LU',
    },
    {
        'nome': 'Donazione Sangue',
        'richiesta_dipendente': True,
        'richiede_approvazione': False,
        'richiede_id_nazionale': True,
        'codice_assenza':  'DS',
    }
]


def crea_tipi_assenza_fissi(apps, schema_editor):
    """
    Funzione eseguita in fase di avanzamento (forward) della migrazione.
    Inserisce i tipi di assenza se non esistono.
    """
    TipoAssenza = apps.get_model('assenze', 'TipoAssenza')
    
    for data in TIPI_ASSENZA_INIZIALI:
        nome_assenza = data['nome']
        
        # Logica di Idempotenza: crea solo se il record non esiste
        if not TipoAssenza.objects.filter(nome=nome_assenza).exists():
            TipoAssenza.objects.create(**data)

            print(f"Creato TipoAssenza: {nome_assenza}")
        else:
            print(f"TipoAssenza: {nome_assenza} già esistente. Salto la creazione.")


def elimina_tipi_assenza_fissi(apps, schema_editor):
    """
    Funzione eseguita in caso di rollback (reverse) della migrazione.
    Elimina i tipi di assenza inseriti, assumendo che i nomi siano univoci.
    """
    TipoAssenza = apps.get_model('contratti', 'TipoAssenza')
    
    nomi_da_eliminare = [data['nome'] for data in TIPI_ASSENZA_INIZIALI]
    
    deleted_count, _ = TipoAssenza.objects.filter(nome__in=nomi_da_eliminare).delete()
    print(f"Eliminati {deleted_count} TipoAssenza in fase di rollback.")

class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0003_tipoassenza_richiesta_dipendente'),
    ]

    operations = [
        migrations.RunPython(crea_tipi_assenza_fissi, elimina_tipi_assenza_fissi),
    ]